# Butterfly theme overrides

nav:
  logo:
  display_title: true
  fixed: false

menu:
  首页: / || fas fa-home
  归档: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  目录: /categories/ || fas fa-folder-open
  友情链接: /link/ || fas fa-link
  关于我们: /about/ || fas fa-heart

favicon: /img/6a171e739399e.webp

avatar:
  img: /img/6a171e739399e.webp
  effect: false

# 只保留网站背景图，禁用所有横幅图。
disable_top_img: true
index_img:
default_top_img:
archive_img:
tag_img:
tag_per_img:
category_img:
category_per_img:

cover:
  index_enable: true
  aside_enable: true
  archives_enable: true
  position: both
  default_cover:
    - /img/2C362DA6D735F84109D390378D24911C.jpg
    - /img/6a1a50eecd3e4.webp
    - /img/6a1a50f0643f4.webp

error_img:
  flink: /img/friend_404.gif
  post_page: /img/404.jpg

background: /img/6a171ccc7819f.webp
footer_bg: transparent

mask:
  header: true
  footer: true

aside:
  enable: true
  hide: false
  button: true
  mobile: true
  position: right
  display:
    archive: true
    tag: true
    category: true
  card_author:
    enable: true
    description: Wa1ex的个人博客
    button:
      enable: true
      icon: fab fa-github
      text: 关注我
      link: https://github.com/soy-saber

announcement:
  enable: true
  content: 没有公告

highlight_theme: light
highlight_copy: true
highlight_lang: true
highlight_shrink: false
highlight_fullpage: true

inject:
  head:
    - <link rel="stylesheet" href="/css/custom.css">
  bottom:
